version: '2'
services:
  go:
    build: .
    volumes:
      - .:/go/src/mq-duplicate-stats
    working_dir: /go/src/mq-duplicate-stats
    command: go run main.go
    links:
      - redis
    environment:
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine
    volumes:
      - /tmp/redis/data:/data